name: CI
on:
  push:
    branches: [ deploy ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install texlive
        run: sudo apt install texlive-base 
      - name: Install texlive-latex-extra
        run: sudo apt-get install texlive-latex-extra
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        run: |
          python main.py
      - name: Build pdf
        run: pdflatex -aux-directory=log/ -output-directory=output/ output/resume.tex
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[automated] Generate PDF from resume.tex"
      - uses: repo-sync/pull-request@v2
        name: Create Pull Request
        with:
          destination_branch: "master"
          pr_title: "[automated] Merge PDF into master"
          pr_body: "Automated PR after generating resume pdf with pdflatex build"
          pr_label: "automated-pdf"
          github_token: ${{ secrets.GITHUB_TOKEN }}
